### ISSUE TITLE
Tabs?

### ISSUE THREAD

**Issue by asciideer** [c3lang/c3-ts-mode#1]
Doesn't seem to support indentation with tabs for some reason?

Or i couldn't find how to do it, only option for indentation that i see is `C3 Ts Mode Indent Offset` which is for indentation with spaces.

**Comment by cbuttner** [comment]
It works for tabs too, this may be an issue of your Emacs configuration defaulting to spaces.
You can try toggling the `indent-tabs-mode` variable: https://www.emacswiki.org/emacs/IndentationBasics

**Comment by asciideer** [comment]
i have indent-tabs-mode off by default but enabled manually, it's even in the `(add-hook 'c3-ts-mode-hook (lambda () (indent-tabs-mode t)))` but it still seems to use 2 spaces instead of tabs.

it happens in `emacs -q` too with
```elisp
(setq treesit-language-source-alist
      '((c3 "https://github.com/c3lang/tree-sitter-c3")))

(add-to-list 'load-path "~/.config/emacs/cmade/c3-ts-mode")
(require 'c3-ts-mode)
```

**Comment by cbuttner** [comment]
Just to clarify, `c3-ts-mode-indent-offset` is not just for spaces.
Here's what could be happening, your `c3-ts-mode-indent-offset` needs to be at least `tab-width` for it to actually use tabs everywhere.
So when your `tab-width` is 4 but `c3-ts-mode-indent-offset` is 2, it doesn't work at the first level of indentation, because it can't fill up 2 spaces with one tab that is 4 spaces wide.

**Comment by asciideer** [comment]
that makes sense now, thanks!
